name: Deploy Next.js to Hostido

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v4

      - name: Ustaw Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Zainstaluj zależności
        run: npm install

      - name: Zbuduj projekt
        run: npm run build

      - name: Wgraj na Hostido przez FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /public_html/